data_process:
  path: ../custom_processors.py
  processors:
    - extract_observed_feature: {feature_name: first_is_chosen} # binary outcome
    - extract_predictors: {predictor_names: ['llm_pair', 'grader'], effect_coding_for_main_effects: true, interactions: true}
    - extract_features: {feature_names: [length_diff], standardise: true}

model:
  path: ../custom_model.py
  models:
    - name: pairwise_logistic_model
      config:
        tag: with_length_diff
        main_effects: ['llm_pair', 'grader', 'length_diff']
        effect_coding_for_main_effects: true
    - name: pairwise_logistic_model
      config:
        tag: without_length_diff
        main_effects: ['llm_pair', 'grader']
        effect_coding_for_main_effects: true
check:
  checkers:
    - prior_predictive_plot
    - divergences
    - r_hat
    - ess_bulk
    - ess_tail
    - posterior_predictive_plot
    - waic

communicate:
  path: ../custom_communicators.py
  communicators:
    - forest_plot: {vars: ["grader_effects", "llm_pair_effects", "grader_length_slopes"], combined: true, vertical_line: 0}
    - summary_table
    - model_comparison_plot
