stages:
  load: # for this example we are starting with a csv therefore no need for hibayes-load
    cmd: python get_csvs.py --csv files/data.csv --out .output/load/
    deps:
    - get_csvs.py
    outs:
    - .output/load/
  model:
    cmd: hibayes-model --config files/config.yaml --data .output/load/data.csv
      --out .output/model/
    deps:
    - ../../src/hibayes/
    - .output/load/data.csv
    outs:
    - .output/model/
    params:
      - files/config.yaml:
        - model
        - checkers
        - platform
  communicate:
    cmd: hibayes-comm --config files/config.yaml --analysis_state .output/model/ --out
      .output/communicate/
    deps:
    - ../../src/hibayes/
    - .output/model/
    outs:
    - .output/communicate/
    params:
      - files/config.yaml:
        - communicate
