data_loader:
  paths:
    files_to_process:
      - s3://aisi-data-eu-west-2-prod/teams/soe/cybench-alt.eval
      - s3://aisi-data-eu-west-2-prod/teams/soe/cybench-basic.eval
      #- s3://aisi-data-eu-west-2-prod/teams/ru/agents/ws-agents/project-2025-q1-fine-tuning/2025-03-24T16-25-25/3f1c7ae17a1f128a2901431616c5985ae3ca7c3b/2025-03-24T16-25-32+00-00_cybench_SRPDmkNWkUAZ3ZhJnfnXXV.eval
      #- s3://aisi-data-eu-west-2-prod/teams/ru/agents/ws-agents/project-2025-q1-fine-tuning/2025-03-13T10-15-12/bad1cba240c3029c4e67f51612911a87ed09c9c4/2025-03-13T10-15-20+00-00_cybench_XUEnmgDF6iwa2LcAa6WxwJ.eval
      #- s3://aisi-data-eu-west-2-prod/teams/ru/agents/ws-agents/project-2025-q1-think/2025-04-04T09-40-24/926c0b51b20c3615904ce296d196492181158cdc/2025-04-04T09-40-29+00-00_cybench_4LieCvsTh45izf2q46Quds.eval
      #- s3://aisi-data-eu-west-2-prod/teams/ru/agents/ws-agents/project-2025-q1-fine-tuning/2025-03-07T12-05-01/bad1cba240c3029c4e67f51612911a87ed09c9c4/2025-03-07T12-05-07+00-00_cybench_KES9LdKUyAJModWsdwmxic.eval
      #- s3://aisi-data-eu-west-2-prod/teams/ru/agents/ws-agents/project-2025-q1-fine-tuning/2025-03-11T12-27-52/bad1cba240c3029c4e67f51612911a87ed09c9c4/2025-03-11T12-27-56+00-00_cybench_dTUz47tRDtcArMmpYu2hBZ.eval
      #- s3://aisi-data-eu-west-2-prod/teams/ru/agents/ws-agents/project-2025-q1-think/2025-04-04T09-40-33/926c0b51b20c3615904ce296d196492181158cdc/2025-04-04T09-40-39+00-00_cybench_cRA9heRcYoybfEjtneVpaq.eval
      #- s3://aisi-data-eu-west-2-prod/teams/ru/agents/ws-agents/project-2015-q1-cyber-elicitation/2025-02-17T11-24-16/bd78efb985867e7c08d6da89131210710ecf5d95/2025-02-17T11-24-19+00-00_cybench_SBQVW8Di5U4JPVZPWwevv2.eval
  extractors:
    enabled:
      - base
      - tokens
      - tools
    custom:
      path: examples/cybench/files/extractors.py
      classes:
        - LogFileNameExtractor
model:
  models:
    ModelBinomial:
    ModelBetaBinomial:
    ModelBetaBinomialwSetup:
platform:
checkers:
  checks:
    - prior_predictive_plot
    - r_hat
    - divergences
    - ess_bulk
    - ess_tail
    - loo
    - bfmi
    - posterior_predictive_plot: {plot_proportion: true}
    - waic
communicate:
  forest_plot: {combined: true}