data_process:
  processors:
    - extract_observed_feature: {feature_name: score} # 0-10 rating
    - extract_predictors: {predictor_names: [grader, LLM], effect_coding_for_main_effects: true, interactions: true}

model:
  models:
    - name: ordered_logistic_model
      config:
        tag: with_interaction
        main_effects: ["grader", "LLM"]
        interactions: [["grader", "LLM"]]
        num_classes: 11  # for 0-10 scale
        effect_coding_for_main_effects: true
        fit:
          samples: 2000
          chains: 4
    - name: ordered_logistic_model
      config:
        tag: without_interaction
        main_effects: ["grader", "LLM"]
        num_classes: 11
        effect_coding_for_main_effects: true
        fit:
          samples: 2000
          chains: 4
check:
  checkers:
    - prior_predictive_plot: {interactive: false}
    - divergences
    - r_hat
    - ess_bulk
    - ess_tail
    - posterior_predictive_plot: {interactive: false}
    - waic

communicate:
  path: ../custom_communicators.py
  communicators:
    - cutpoint_plot
    - ordered_residuals_plot
    - category_frequency_plot
    - forest_plot: {vars: ["grader_effects", "LLM_effects", "grader_LLM_effects"], combined: true, vertical_line: 0}
    - forest_plot: {combined: true, vertical_line: 0}
    - summary_table
    - model_comparison_plot
