data_loader:
  paths:
    files_to_process:
      - data/

  extractors:
    enabled:
      - base
    custom:
      path: files/custom_extractor.py
      classes:
        - Domains
model:
  models:
    - name: BetaBinomial
      config:
        tag: version_1
        column_map:
          Sample ID: task
        random_effects:
          - name: task_effects
            groups: ["task"]
            prior:
              distribution: normal
              distribution_params:
                loc: 0
                scale: 0.5
          - name: model
            groups: ["model"]
            prior:
              distribution: normal
              distribution_params:
                loc: 0
                scale: 0.5
          - name: task_model_effects
            groups: ["task", "model"]
            prior:
              distribution: normal
              distribution_params:
                loc: 0
                scale: 0.5
    - name: BetaBinomial
      config:
        tag: version_2
        column_map:
          Sample ID: task
        random_effects:
          - name: task_effects
            groups: ["task"]
            prior:
              distribution: normal
              distribution_params:
                loc: 0
                scale: 0.5
          - name: model
            groups: ["model"]
            prior:
              distribution: normal
              distribution_params:
                loc: 0
                scale: 0.5
    - name: Binomial
      config:
        column_map:
          Sample ID: task
        random_effects:
          - name: task_effects
            groups: ["task"]
            prior:
              distribution: normal
              distribution_params:
                loc: 0
                scale: 0.5
          - name: model
            groups: ["model"]
            prior:
              distribution: normal
              distribution_params:
                loc: 0
                scale: 0.5



platform:
checkers:
  checks:
    - prior_predictive_plot
    - r_hat
    - divergences
    - ess_bulk
    - ess_tail
    - loo
    - bfmi
    - posterior_predictive_plot: {plot_proportion: true, kind: "hist"}
    - waic
communicate:
  forest_plot: {combined: true}
