data_loader:
  paths:
    files_to_process:
      - data/gpt-4o

  extractors:
    enabled:
      - base
    custom:
      path: files/custom_extractor.py
      classes:
        - Domains
data_process:
  processors:
    - map_columns: {column_mapping: {domain: group}}
    - groupby: {groupby_columns: [group]}
    - extract_features: {feature_names: [n_total]}
    - extract_predictors: {predictor_names: [group]}
    - extract_observed_feature: {feature_name: n_correct}

model:
  models:
    - name: two_level_group_binomial
      config:
        tag: version_1

platform:
check:
  checkers:
    - prior_predictive_plot: {plot_proportion: true}
    - r_hat
    - divergences
    - ess_bulk
    - ess_tail
    - loo
    - bfmi
    - posterior_predictive_plot: {plot_proportion: true, plot_kwargs: {num_pp_samples: 50}}
    - waic
communicate:
  communicate:
    - forest_plot: {combined: true}
    - trace_plot
    - summary_table
