stages:
  load:
    cmd: hibayes-load --config files/config.yaml --out .output/load/
    deps:
    - ../../src/hibayes/
    - files/custom_extractor.py
    outs:
    - .output/load/
    params:
      - files/config.yaml:
        - data_loader

  process:
    cmd: hibayes-process --config files/config.yaml --data .output/load/data.parquet --out .output/process/
    deps:
    - ../../src/hibayes/
    - .output/load/data.parquet
    outs:
    - .output/process/
    params:
      - files/config.yaml:
        - data_process
  model:
    cmd: hibayes-model --config files/config.yaml --analysis-state .output/process/ --out .output/model/
    deps:
    - ../../src/hibayes/
    - .output/process/
    outs:
    - .output/model/
    params:
      - files/config.yaml:
        - model
        - check
        - platform
  communicate:
    cmd: hibayes-comm --config files/config.yaml --analysis_state .output/model/ --out .output/communicate/
    deps:
    - ../../src/hibayes/
    - .output/model/
    outs:
    - .output/communicate/
    params:
      - files/config.yaml:
        - communicate
