# noting that this example is only accessible to internal AISI users - will soon be able to share internal inspect logs for examples.
data_loader:
  paths:
    files_to_process:
      - s3://aisi-data-eu-west-2-prod/users/harry-coppock/reasoning/gaia/7/
  extractors:
    enabled:
      - base
      - tokens
      - tools
    custom:
      path: files/extractors.py
      classes:
        - GaiaMetadataExtractor
data_inspector:
  inspectors:
    - ModelInspector
    - ScoreInspector
    - TokenInspector
    - MissingValuesInspector
  thresholds:
    imbalance: 0.1
    missing: 0.1
model:
  models:
    ModelSampleEffects:
      mapping_name:
        score: success
        task: sample
      fit:
        chains: 4
        samples: 1000
        warmup: 500

checkers:
  custom_checks:
    path: files/custom_checker.py
    checks:
      - posterior_mean_positive: {param: mu_overall, threshold: 0}
  checks:
      - prior_predictive_plot
      - r_hat
      - divergences
      - ess_bulk
      - ess_tail
      - loo
      - bfmi
      - posterior_predictive_plot
      - waic
platform:
communicate:
